### ISSUE TITLE
RealTime Imaging module leak

### ISSUE THREAD

**Issue by tokjun** [openigtlink/VolumeResliceDriver#1]
This was originally posted by Laurent Chauvin at Slicer's bug reporting system:

When I use RealTime Imaging with a vtkMRMLScalarVolumeNode and change the vtkImageData inside, it's creating a vtkMatrix4x4 leaks when leaving Slicer.

To fix it, just change these lines:

In qSlicerReslicePropertyWidget.cxx - void updateSliceByTransformNode
  vtkSmartPointer<vtkMatrix4x4> transform = vtkMatrix4x4::New();

In qSlicerReslicePropertyWidget.cxx - void updateSliceByImageNode
  vtkSmartPointer<vtkMatrix4x4> rtimgTransform = vtkMatrix4x4::New();

By respectively this:
  vtkSmartPointer<vtkMatrix4x4> transform = vtkSmartPointer<vtkMatrix4x4>::New();

  vtkSmartPointer<vtkMatrix4x4> rtimgTransform = vtkSmartPointer<vtkMatrix4x4>::New();

**Comment by lchauvin** [comment]
I updated the source code to add vtkSmartPointer<> around vtkMatrix4x4 to avoid leaks.
