### ISSUE TITLE
Compilation error due to module renaming

### ISSUE THREAD

**Issue by ungi** [openigtlink/VolumeResliceDriver#2]
I tried to compile "VolumeResliceDriver" module from the github.
The code looks messed up and it doesn't compile.

E.g.
In file: VolumeResliceDriver\CMakeLists.txt
There is:
set(qt_module_SRCS
  qSlicerRealTimeImagingModule.cxx
  qSlicerRealTimeImagingModule.h
  qSlicerRealTimeImagingModuleWidget.cxx
  qSlicerRealTimeImagingModuleWidget.h
...

But there are no such files in the module anymore. RealTimeImaging seems to be changed to VolumeResliceDriver in the file names.

**Comment by lchauvin** [comment]
Class and files has been renamed to be coherent.
