### ISSUE TITLE
VolumeResliceDriver cannot be installed from Extension Manager

### ISSUE THREAD

**Issue by tokjun** [openigtlink/VolumeResliceDriver#4]
VolumeResliceDriver is listed in the SlicerExtensions interface in Slicer 4, but it cannot be installed from there.

Once a user click the "INSTALL" button, the progress bar appears in the window and show that the Slicer downloads the package. However, the button doesn't change to "INSTALLED" state even after the progress bar disappears.

**Comment by tokjun** [comment]
I tried it with Slicer r20721 built on my Mac OS X (10.7.0). The console shows the following error:

```
"Retrieving extension metadata [ extensionId: 3322]" 
"Downloading extension [ itemId: 5262]" 
ctk::copyDirRecursively: Failed to copy nonexistent directory "/Users/junichi/igtdev/slicer4/Slicer-SuperBuild-Debug/Slicer-build/bin/Slicer.app/Contents/Extensions/VolumeResliceDriver/20721-macosx-amd64-MyExtension-git5269e2f-2012-08-03/Slicer.app/Contents/Extensions/VolumeResliceDriver" 
```

**Comment by tokjun** [comment]
It turned out that EXTENSION_NAME variable in CMakeLists.txt was not correctly set. It has been fixed in commit f9168e609a3cc710207aede6e719e78b5ed01511.

**Comment by lchauvin** [comment]
Is it fixed ? Could we close the issue ?

**Comment by ungi** [comment]
I can install this module on Windows, so I think this ticket could be closed.
